# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Submodules
      run: |
        git submodule update --init --recursive
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Copy to production
      run: |        
        if [ ! -d '/home/inDrive/projects/backend' ]; then
            mkdir /home/inDrive/projects/backend
        fi
        
        cp -r /home/inDrive/actions-runner/_work/inDrive/inDrive/backend /home/inDrive/projects/backend
        
        if [ ! -d '/home/inDrive/projects/frontend/' ]; then
            mkdir /home/inDrive/projects/frontend/
        fi
        
        cp -r /home/inDrive/actions-runner/_work/inDrive/inDrive/frontend /home/inDrive/projects/frontend
